import vm from 'node:vm';
import _traverse, { type NodePath } from '@babel/traverse';
import type * as t from '@babel/types';
import { obfuscate } from 'javascript-obfuscator';
import { describe, expect, it } from 'vitest';
import { buildDecoder } from '../src/analysis/evaluator/index.js';
import { recogniseNativeDecoder, recogniseRotationPuzzle } from '../src/analysis/evaluator/native.js';
import { sliceForEvaluation } from '../src/analysis/slice.js';
import { resolveConfig } from '../src/config/presets.js';
import { parseSource } from '../src/frontend/language.js';
import { deobfuscate } from '../src/index.js';
import type { Severity } from '../src/types.js';

const traverse = ((_traverse as unknown as { default?: typeof _traverse }).default ??
  _traverse) as typeof _traverse;

/**
 * A rotation loop the recogniser solves as arithmetic is the one place a
 * slice's own initialisation outruns the interpreter's budget: every turn
 * decodes one string per checksum term, and an rc4 build with chained
 * wrappers takes hundreds of turns over a dozen terms. The native match is
 * confirmed by the interpreter run past the loop - its solution stood in
 * for it, the checksum's own terms among the sites compared - and only
 * when the loop body is the puzzle and nothing else.
 */

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

function execute(code: string, timeout = 5_000): string {
  const trace: string[] = [];
  const timers: (() => void)[] = [];
  const log = (...args: unknown[]): void => {
    trace.push(args.map((value) => (typeof value === 'string' ? JSON.stringify(value) : String(value))).join(' '));
  };
  const queue = (fn: () => void): number => timers.push(fn);
  try {
    vm.runInNewContext(
      code,
      vm.createContext({ log, setTimeout: queue, setInterval: queue, clearInterval: () => undefined, clearTimeout: () => undefined }),
      { timeout },
    );
    for (let drained = 0; timers.length > 0 && drained < 32; drained++) timers.shift()!();
  } catch (error) {
    trace.push(`THROWN ${(error as Error).name}: ${(error as Error).message}`);
  }
  return trace.join('\n');
}

const PRESETS = ['conservative', 'balanced', 'aggressive'] as const;

function programPath(source: string): NodePath<t.Program> {
  const { ast } = parseSource(source);
  let found: NodePath<t.Program> | undefined;
  traverse(ast, {
    Program(path) {
      found = path;
      path.stop();
    },
  });
  if (!found) throw new Error('no Program path');
  found.scope.crawl();
  return found;
}

function build(
  source: string,
  roots: string[],
  options: Parameters<typeof resolveConfig>[0] = {},
  samples?: readonly (readonly (string | number)[])[],
) {
  const notes: { severity: Severity; message: string }[] = [];
  const decoder = buildDecoder(programPath(source), roots, resolveConfig(options), {
    reporter: { note: (severity, message) => notes.push({ severity, message }) },
    ...(samples ? { samples } : {}),
  });
  return { decoder, notes };
}

const CONFIRMED = /Confirmed the "(.+)" match for (\S+) by the interpreter on (\d+) of (\d+) call site\(s\) and on the (\d+) term\(s\) of the rotation checksum, run past the rotation loop with the (\d+) shift\(s\) it solves to/;

// ---------------------------------------------------------------------------
// The template, generated by javascript-obfuscator
// ---------------------------------------------------------------------------

const MODERN = `class Vessel { #mask = 170; constructor(hex) { this.hex = hex; } *unmask() { for (const ch of this.hex.match(/../g)) yield (parseInt(ch, 16) ^ this.#mask).toString(16).padStart(2, '0'); } static from(h) { return new Vessel(h); } } const v = Vessel.from('d3cbed8acf'); const out = [...v.unmask()].map(x => x.toUpperCase()).join(':'); const tag = (s, ...a) => s.raw.join('|') + a.length; log(out, tag\`a\${1}b\${2}\`, typeof Vessel, JSON.stringify({ k: [1, 'two', null] }));`;

/** rc4 over three chained function wrappers: the rotation checksum decodes a dozen strings per turn. */
const RC4_CHAINED = {
  stringArray: true,
  stringArrayThreshold: 1,
  stringArrayEncoding: ['rc4' as const],
  stringArrayWrappersCount: 3,
  stringArrayWrappersType: 'function' as const,
  stringArrayWrappersChainedCalls: true,
  stringArrayWrappersParametersMaxCount: 4,
};

function layered(source: string, layers: number): string {
  let current = source;
  for (let layer = 1; layer <= layers; layer++) {
    current = obfuscate(current, { ...RC4_CHAINED, seed: 20260920 + layer }).getObfuscatedCode();
  }
  return current;
}

describe('an rc4 build whose rotation loop outruns the interpreter', () => {
  const expected = execute(MODERN);

  for (const layers of [1, 3]) {
    it(`is confirmed past the loop and decoded at every preset, ${layers} layer(s) deep`, async () => {
      const source = layered(MODERN, layers);
      expect(execute(source)).toBe(expected);
      for (const preset of PRESETS) {
        const result = await deobfuscate(source, { preset, performance: { maxIterations: 12 } });
        expect(execute(result.code), preset).toBe(expected);
        const messages = result.metadata.diagnostics.map((d) => `${d.severity} ${d.message}`);
        // Three layers deep the outermost rotation takes hundreds of turns
        // over eleven rc4 terms: forty-eight million interpreter steps
        // before the first call site, against a budget of twenty. The match
        // used to stand unchecked at balanced with a warning, and be refused
        // at conservative with nothing decoded.
        expect(messages.filter((m) => m.startsWith('warning') || m.startsWith('error')), preset).toEqual([]);
        expect(messages.some((m) => m.includes('stands unchecked') || m.includes('ran out of budget')), preset).toBe(false);
        const confirmed = messages.filter((m) => CONFIRMED.test(m));
        expect(confirmed.length, `${preset}: ${messages.join('\n')}`).toBeGreaterThanOrEqual(layers);
        for (const line of confirmed) {
          const [, evidence = '', , checked, of, terms, shifts] = CONFIRMED.exec(line)!;
          expect(evidence).toMatch(/^rc4 \(256-entry KSA\/PRGA over base64\), index offset \d+, rotation \d+$/);
          expect(evidence.endsWith(`rotation ${shifts}`)).toBe(true);
          expect(Number(checked)).toBeGreaterThan(0);
          expect(Number(checked)).toBeLessThanOrEqual(Number(of));
          expect(Number(terms)).toBeGreaterThanOrEqual(8);
        }
        expect(result.metadata.strings.length, preset).toBeGreaterThanOrEqual(layers === 1 ? 18 : 200);
        expect(result.code, preset).not.toMatch(/\b_0x[0-9a-f]+\((0x)?[0-9a-f]+/);
        expect(result.code, preset).not.toMatch(/while\s*\(\s*(true|!!\[\])\s*\)/);
        expect(result.code).toContain('toUpperCase');
      }
    });
  }
});

// ---------------------------------------------------------------------------
// The loop stood in for by its solution is the puzzle and nothing else
// ---------------------------------------------------------------------------

/** Forty entries, the two numeric ones last: the checksum balances after thirty-eight shifts. */
const ENTRIES = Array.from({ length: 38 }, (_, i) => `'w${i}'`).concat(["'300'", "'400'"]).join(', ');

const rotating = (loop: string, decoder = 'return _0xt[_0xi];'): string => `
  var _0xt = [${ENTRIES}];
  var cnt = 0;
  (function (_0xp, _0xq) {
    var _0xr = _0xd;
    ${loop}
  }(_0xt, 500));
  function _0xd(_0xi) { ${decoder} }
  log(_0xd(2), _0xd(3));
`;

const TEMPLATE_LOOP = `while (!![]) { try { var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { _0xp['push'](_0xp['shift']()); } }`;

function puzzleOf(source: string) {
  const program = programPath(source);
  const slice = sliceForEvaluation(program, ['_0xd', '_0xt']);
  return { puzzle: recogniseRotationPuzzle(slice.statements, new Set(['_0xd'])), native: recogniseNativeDecoder(slice, ['_0xd', '_0xt']) };
}

describe('the loop stood in for by its solution', () => {
  it('is exact when its body is the try/catch, the checksum, the comparison and the shuffle', () => {
    const shapes: Record<string, string> = {
      'the template': TEMPLATE_LOOP,
      'the comparison in block form': `while (true) { try { var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) { break; } else { _0xp['push'](_0xp['shift']()); } } catch (_0xe) { _0xp['push'](_0xp['shift']()); } }`,
      'a for(;;) with no try': `for (;;) { var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; _0xp.push(_0xp.shift()); }`,
      'the loose comparison and a !0 test': `while (!0) { try { var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xq == _0xc) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { _0xp['push'](_0xp['shift']()); } }`,
    };
    for (const [what, loop] of Object.entries(shapes)) {
      const source = rotating(loop);
      expect(execute(source), what).toBe('"w0" "w1"');
      const { puzzle, native } = puzzleOf(source);
      expect(puzzle?.exact, what).toBe(true);
      expect(native?.solvedRotation?.shifts, what).toBe(38);
      expect(native?.solvedRotation?.terms, what).toEqual([[0], [1]]);
      for (const preset of PRESETS) {
        const { decoder, notes } = build(source, ['_0xd', '_0xt'], { preset, sandbox: { maxSteps: 1_500 } });
        expect(decoder?.tier, `${what} at ${preset}`).toBe('native');
        expect(notes.some((note) => CONFIRMED.test(note.message)), `${what} at ${preset}: ${notes.map((n) => n.message).join('\n')}`).toBe(true);
        expect(notes.some((note) => note.message.includes('stands unchecked')), `${what} at ${preset}`).toBe(false);
      }
    }
  });

  it('is not exact, and the whole slice is run instead, when anything else turns with it', async () => {
    const shapes: Record<string, { loop: string; prints: RegExp; refused: string; helper?: string }> = {
      'a call the recogniser did not read on every turn': {
        loop: `while (!![]) { try { heavy(); var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { if (_0xe.message === 'boom') throw _0xe; _0xp['push'](_0xp['shift']()); } }`,
        prints: /^THROWN Error: boom$/,
        refused: 'in a call the recogniser did not read',
        helper: "function heavy() { var s = 'x'.repeat(20000).length; if (++cnt > 2) throw new Error('boom'); return s; }\n",
      },
      'a recursion on every turn': {
        loop: `while (!![]) { try { (function r(n) { if (++cnt > 30000) throw new Error('boom'); return n > 12 ? 0 : r(n + 1) + r(n + 1); })(0); var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { if (_0xe.message === 'boom') throw _0xe; _0xp['push'](_0xp['shift']()); } }`,
        prints: /^THROWN Error: boom$|timed out/,
        refused: 'in a recursion',
      },
      'a counter the loop keeps': {
        loop: `while (!![]) { try { cnt++; var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { _0xp['push'](_0xp['shift']()); } }`,
        prints: /^"w0" "w1"$/,
        refused: 'ran out of budget',
      },
      'a test that runs something': {
        loop: `while (cnt++ < 1e9) { try { var _0xc = parseInt(_0xr(0x0)) / 0x1 + parseInt(_0xr(0x1)) / 0x2; if (_0xc === _0xq) break; else _0xp['push'](_0xp['shift']()); } catch (_0xe) { _0xp['push'](_0xp['shift']()); } }`,
        prints: /^"w0" "w1"$/,
        refused: 'ran out of budget',
      },
    };
    for (const [what, { loop, prints, refused, helper }] of Object.entries(shapes)) {
      const source = (helper ?? '') + rotating(loop);
      expect(execute(source), what).toMatch(prints);
      const { puzzle, native } = puzzleOf(source);
      expect(puzzle?.exact, what).toBe(false);
      expect(native?.solvedRotation, what).toBeUndefined();
      // The whole slice is run, as before, and judged as before: the budget
      // it runs out of is spent where the recogniser did not read, or in a
      // loop it did, and the match stands or is refused on that alone.
      for (const preset of PRESETS) {
        const { notes } = build(source, ['_0xd', '_0xt'], { preset, sandbox: { maxSteps: 1_500 } });
        const said = `${what} at ${preset}: ${notes.map((n) => n.message).join('\n')}`;
        expect(notes.some((note) => CONFIRMED.test(note.message)), said).toBe(false);
        expect(notes.some((note) => note.message.includes('ran out of budget while building')), said).toBe(true);
        expect(notes.some((note) => note.message.includes(refused)), said).toBe(true);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// The check spends one budget
// ---------------------------------------------------------------------------

describe('the check past the loop', () => {
  it('falls back to the whole slice, and its verdicts, when it cannot finish either', async () => {
    const source = rotating(TEMPLATE_LOOP);
    // A hundred steps decode nothing: the check is silent, the whole slice
    // runs out of budget in the loop the recogniser read, and the match
    // stands at balanced with the warning and is refused at conservative.
    const stood = build(source, ['_0xd', '_0xt'], { preset: 'balanced', sandbox: { maxSteps: 100 } });
    expect(stood.decoder?.tier).toBe('native');
    expect(stood.notes.some((note) => note.message.includes('stands unchecked'))).toBe(true);
    expect(stood.notes.some((note) => CONFIRMED.test(note.message))).toBe(false);
    const refused = build(source, ['_0xd', '_0xt'], { preset: 'conservative', sandbox: { maxSteps: 100 } });
    expect(refused.decoder).toBeUndefined();
    expect(refused.notes.some((note) => note.message.includes('conservative preset inlines only what is proved'))).toBe(true);
  });

  it('cuts the spread to what the budget affords past the head, and always compares the checksum terms', () => {
    // Three hundred and four distinct sites over forty entries, a plain
    // lookup a handful of steps each: the head of thirty-two measures a
    // call, and the rest is spread over what is left of a thousand steps.
    // The two terms of the checksum are compared whatever the budget, and
    // are not sites of the program at all.
    const sites: (readonly (string | number)[])[] = [];
    for (let k = 0; k < 8; k++) for (let i = 2; i < 40; i++) sites.push([i, k]);
    const uses = sites.map(([i, k]) => `_0xd(${i}, ${k})`).join(', ');
    const source = `
      var _0xt = [${ENTRIES}];
      (function (_0xp, _0xq) {
        var _0xr = _0xd;
        ${TEMPLATE_LOOP}
      }(_0xt, 500));
      function _0xd(_0xi, _0xk) { return _0xt[_0xi]; }
      log(${uses});
    `;
    const distinct = new Set(sites.map((s) => s.join(','))).size;
    const tight = build(source, ['_0xd', '_0xt'], { preset: 'balanced', sandbox: { maxSteps: 1_000 } }, sites);
    expect(tight.decoder?.tier).toBe('native');
    const tightLine = tight.notes.map((n) => n.message).find((m) => CONFIRMED.test(m))!;
    expect(tightLine, tight.notes.map((n) => n.message).join('\n')).toBeDefined();
    const [, , , checked, of, terms] = CONFIRMED.exec(tightLine)!;
    expect(Number(of)).toBe(distinct);
    expect(Number(checked)).toBeGreaterThanOrEqual(32);
    expect(Number(checked)).toBeLessThan(distinct);
    expect(Number(terms)).toBe(2);

    const wide = build(source, ['_0xd', '_0xt'], { preset: 'balanced' }, sites);
    const wideLine = wide.notes.map((n) => n.message).find((m) => CONFIRMED.test(m))!;
    expect(Number(CONFIRMED.exec(wideLine)![3])).toBe(distinct);
  });
});
